# Generated by Django 5.0.1 on 2025-02-20 16:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos_preg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID códigos preguntas')),
                ('codigo_preguntas', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('cod_provincia', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Cod provincia')),
                ('nombre_provincia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('cod_region', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Cod region')),
                ('nombre_region', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RespTextoFRM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID índice antropométrico')),
                ('Rut', models.CharField(max_length=10)),
                ('peso_FRM6', models.CharField(max_length=3)),
                ('altura_FRM5', models.CharField(max_length=4)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PregDeterSalud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Determinantes sociales salud')),
                ('pregunta_DS', models.CharField(max_length=200)),
                ('codigo_preguntas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.codigos_preg')),
            ],
        ),
        migrations.CreateModel(
            name='OpcDeterSalud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Opc determinantes salud')),
                ('opc_respuesta_DS', models.CharField(max_length=200)),
                ('id_pregunta_DS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.pregdetersalud')),
            ],
        ),
        migrations.CreateModel(
            name='PregFactorRiesgoMod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Factor de Riesgo Mod')),
                ('pregunta_FRM', models.CharField(max_length=200)),
                ('codigo_preguntas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.codigos_preg')),
            ],
        ),
        migrations.CreateModel(
            name='OpcFactorRiesgoMod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Opc Riesgo Mod')),
                ('opc_respuesta_FRM', models.CharField(max_length=200)),
                ('id_pregunta_FRM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.pregfactorriesgomod')),
            ],
        ),
        migrations.CreateModel(
            name='PregFactorRiesgoNoMod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Factor de Riesgo No Mod')),
                ('pregunta_FRNM', models.CharField(max_length=200)),
                ('codigo_preguntas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.codigos_preg')),
            ],
        ),
        migrations.CreateModel(
            name='OpcFactorRiesgoNoMod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Opc Riesgo No Mod')),
                ('opc_respuesta_FRNM', models.CharField(max_length=200)),
                ('id_pregunta_FRNM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.pregfactorriesgonomod')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pregunta')),
                ('pregunta', models.CharField(max_length=200)),
                ('codigo_preguntas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.codigos_preg')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaOpcionRespuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Opcion Respuesta')),
                ('OPC_Respuesta', models.CharField(max_length=200)),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('cod_comuna', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Cod comuna')),
                ('nombre_comuna', models.CharField(max_length=200)),
                ('cod_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.provincia')),
            ],
        ),
        migrations.AddField(
            model_name='provincia',
            name='cod_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.region'),
        ),
        migrations.CreateModel(
            name='RespDeterSalud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Resp determinante salud')),
                ('Rut', models.CharField(max_length=10)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('respuesta_DS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.opcdetersalud')),
            ],
        ),
        migrations.CreateModel(
            name='CalculoFRM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Cálculo FRM')),
                ('Rut', models.CharField(max_length=10)),
                ('altura_mod', models.FloatField(default=0)),
                ('peso_mod', models.FloatField(default=0)),
                ('imc', models.FloatField(default=0.0)),
                ('datos_originales', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='botApp.resptextofrm')),
            ],
        ),
        migrations.CreateModel(
            name='RespUsuarioFactorRiesgoMod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Resp Riesgo Mod')),
                ('Rut', models.CharField(max_length=10)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('respuesta_FRM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.opcfactorriesgomod')),
            ],
        ),
        migrations.CreateModel(
            name='RespUsuarioFactorRiesgoNoMod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Resp Riesgo Mod')),
                ('Rut', models.CharField(max_length=10)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('respuesta_FRNM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.opcfactorriesgonomod')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Usuario')),
                ('id_manychat', models.CharField(max_length=200)),
                ('Rut', models.CharField(max_length=10)),
                ('AnioNacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('Whatsapp', models.CharField(max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Referencia', models.CharField(max_length=200)),
                ('Fecha_Ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('edad', models.IntegerField(default=0)),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=30, null=True)),
                ('Comuna_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='ultima_mamografia_anio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de última mamografía')),
                ('Rut', models.CharField(max_length=10)),
                ('anio_ult_mamografia', models.IntegerField(default=0, verbose_name='Año de última mamografía')),
                ('tiempo_transc_ult_mamografia', models.IntegerField(default=0, verbose_name='Tiempo transcurrido')),
                ('fecha_pregunta', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='resptextofrm',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.usuario'),
        ),
        migrations.CreateModel(
            name='UsuarioRespuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Usuario Respuesta')),
                ('Rut', models.CharField(max_length=10)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('id_opc_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.preguntaopcionrespuesta')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeContenido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Texto')),
                ('texto', models.CharField(max_length=200)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('opcrespDS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.respdetersalud')),
                ('opcrespFRM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.respusuariofactorriesgomod')),
                ('opcrespFRNM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.respusuariofactorriesgonomod')),
                ('opcresUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.usuario')),
                ('opcresTM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.usuariorespuesta')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTextoPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Texto Pregunta')),
                ('Rut', models.CharField(max_length=10)),
                ('texto_pregunta', models.CharField(max_length=200)),
                ('fecha_pregunta', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.usuario')),
            ],
        ),
    ]
