# Generated by Django 5.0.1 on 2025-03-12 19:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos_preg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID códigos preguntas')),
                ('codigo_preguntas', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeContenido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Texto')),
                ('texto', models.CharField(max_length=200)),
                ('fecha', models.DateField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('cod_provincia', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Cod provincia')),
                ('nombre_provincia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('cod_region', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Cod region')),
                ('nombre_region', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PregTamizaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pregunta')),
                ('pregunta', models.CharField(max_length=200)),
                ('codigo_preguntas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.codigos_preg')),
            ],
        ),
        migrations.CreateModel(
            name='OpcTamizaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Opcion Respuesta')),
                ('opc_respuesta_TM', models.CharField(max_length=200)),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.pregtamizaje')),
            ],
        ),
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('cod_comuna', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Cod comuna')),
                ('nombre_comuna', models.CharField(max_length=200)),
                ('cod_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.provincia')),
            ],
        ),
        migrations.AddField(
            model_name='provincia',
            name='cod_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.region'),
        ),
        migrations.CreateModel(
            name='RespUsuarioTamizaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Usuario Respuesta')),
                ('id_manychat', models.IntegerField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('respuesta_TM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.opctamizaje')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_manychat', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Manychat')),
                ('AnioNacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('Whatsapp', models.CharField(max_length=255)),
                ('Referencia', models.CharField(max_length=200)),
                ('Fecha_Ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('edad', models.IntegerField(default=0)),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=30, null=True)),
                ('Comuna_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='ultima_mamografia_anio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de última mamografía')),
                ('anio_ult_mamografia', models.IntegerField(default=0, verbose_name='Año de última mamografía')),
                ('tiempo_transc_ult_mamografia', models.IntegerField(default=0, verbose_name='Tiempo transcurrido')),
                ('fecha_pregunta', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_manychat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='filtro_mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID filtro mensaje')),
                ('mensaje_contenido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.mensajecontenido')),
                ('opcresTM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.respusuariotamizaje')),
                ('opcresUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.usuario')),
            ],
        ),
    ]
