# Generated by Django 5.0.1 on 2025-02-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0002_remove_mensajecontenido_opcrestm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Rut',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Whatsapp',
            field=models.CharField(max_length=255),
        ),
    ]
